# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# https://gist.github.com/AskinNet/0d0d4f7f0ee221f8362af9d9876d021a CheatSheet
# Set title ctrl+shift+alt+t

# wallust-colors
include kitty-colors.conf 

font_family FantasqueSansM Nerd Font Mono Bold
font_size 14.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.9
dynamic_background_opacity 1

confirm_os_window_close 0

# change to x11 or wayland or leave auto
linux_display_server auto


scrollback_lines 10000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

foreground #dddddd
background #000000
cursor #dddddd

allow_remote_control yes
listen_on unix:/tmp/kitty_socket


# debido a zellij es innecesario
map ctrl+shift+l no_op 
# map ctrl+shift+l next_tab
map ctrl+shift+h no_op 
# map ctrl+shift+h previous_tab

map ctrl+shift+k no_op 
# map ctrl+shift+k next_window       
map ctrl+shift+j no_op 
# map ctrl+shift+j previous_window   


# Aumentar/Disminuir ancho
map ctrl+alt+Right increase_window_width
map ctrl+alt+Left decrease_window_width

# Aumentar/Disminuir alto
map ctrl+alt+Up increase_window_height
map ctrl+alt+Down decrease_window_height

map ctrl+shift+space cycle_layout


# Reasignar Ctrl+Shift+T para abrir una nueva pestaña en el mismo directorio
map ctrl+shift+t no_op 
# map ctrl+shift+t launch --type=tab --cwd=current zsh

# Reasignar Ctrl+Shift+Enter para abrir una nueva ventana en el mismo directorio
map ctrl+shift+enter no_op 
# map ctrl+shift+enter launch --type=window --cwd=current zsh



map ctrl+shift+r next_layout

map ctrl+? no_op
map ctrl+shift+/ no_op

# quitar eliminar ventanas con esto
map ctrl+shift+w no_op



