# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D7E4EC
background         #121213
cursor             #798089

active_tab_foreground     #121213
active_tab_background     #D7E4EC
inactive_tab_foreground   #D7E4EC
inactive_tab_background   #121213

active_border_color   #D7E4EC
inactive_border_color #121213
bell_border_color     #13151A

color0      #3A3A3B
color1		#13151A
color2		#14151C
color3		#36424B
color4		#3A4C65
color5		#536775
color6		#6B8696
color7		#BED0DB
color8		#859299
color9		#1A1C22
color10		#1A1C26
color11		#485864
color12		#4D6687
color13		#6F8A9C
color14		#8EB2C8
color15		#BED0DB
